export type User = {
  _id: string;
  id: number;
  name: string;
  display_name: string;
  email: string;
  phone: string;
  account_type: string;
  customer_rank: number;
  roles: string[];
  create_date: Date;
  update_date: Date;
  city: string;
  district: string;
  ward: string;
  street: string;
  company_name: string;
  vat: string;
  representative: string;
  business_license: string;
};
